# Generated by Django 2.2 on 2019-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='age',
        ),
        migrations.AddField(
            model_name='reader',
            name='grade',
            field=models.CharField(default='2015', max_length=20),
        ),
    ]
