# Generated by Django 2.2 on 2019-05-27 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='labelfor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_labels', to=settings.AUTH_USER_MODEL),
        ),
    ]
