# Generated by Django 2.2 on 2019-05-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20190527_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userleaveboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('sendtime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='未读', max_length=10)),
                ('leaver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaver_userleavemessage', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_userleavemessage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
