# Generated by Django 2.2 on 2019-06-01 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_FriendShip', to=settings.AUTH_USER_MODEL)),
                ('fb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_FriendShip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='已申请', max_length=10)),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('deal_time', models.DateTimeField()),
                ('message', models.CharField(max_length=50)),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_friendreceive', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_friendrequest', to=settings.AUTH_USER_MODEL)),
                ('unread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_unreadfriendrequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
