# Generated by Django 2.2 on 2019-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_remove_friendrequest_deal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='message',
            field=models.CharField(default='', max_length=50),
        ),
    ]
