# Generated by Django 2.2 on 2019-06-01 11:39

import book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_userleaveboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(default='中国', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cover', models.ImageField(blank=True, upload_to=book.models.custom_path)),
                ('intro', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='book.Author')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_book', to='users.City')),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wishbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leavemessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('sendtime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='未读', max_length=10)),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_leavemessage', to='book.Book')),
                ('leaver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leaver_leavemessage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Changerequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesttime', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=30)),
                ('statusa', models.CharField(default='已申请', max_length=10)),
                ('statusb', models.CharField(default='已申请', max_length=10)),
                ('booka', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_asbooka', to='book.Book')),
                ('bookb', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_asbookb', to='book.Book')),
                ('reciver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_changereciver', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_changerequest', to=settings.AUTH_USER_MODEL)),
                ('unread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_unreadchangerequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_book', to='book.Press'),
        ),
        migrations.AddField(
            model_name='book',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_book', to='users.School'),
        ),
    ]
