# Generated by Django 2.2 on 2019-06-01 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newChangerequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesttime', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=30)),
                ('statusa', models.CharField(default='已申请', max_length=10)),
                ('statusb', models.CharField(default='已申请', max_length=10)),
                ('booka', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_asbooka', to='book.Book')),
                ('bookb', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_asbookb', to='book.Book')),
                ('reciver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_changereciver', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_changerequest', to=settings.AUTH_USER_MODEL)),
                ('unread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_unreadchangerequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Changerequest',
        ),
    ]
