# Generated by Django 2.2 on 2019-06-01 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_auto_20190601_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newChangerequest',
            new_name='Changerequest',
        ),
    ]
