# Generated by Django 2.2 on 2019-06-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190601_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changerequest',
            old_name='reciver',
            new_name='receiver',
        ),
    ]
