# Generated by Django 2.2 on 2019-05-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190505_1749'),
        ('book', '0003_auto_20190508_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reader_book', to='users.Reader'),
        ),
    ]
