# Generated by Django 2.2 on 2019-06-02 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190602_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_changerecive', to=settings.AUTH_USER_MODEL),
        ),
    ]
